<?
function get_available_stations(){
  //Taken URLs from  http://wiki.ubuntuusers.de/internetradio/stationen 
  $RadioStations =  Array(
            Array( ('name') => "1LIVE",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s25260q.png",
                   ('url')  => "x-rincon-mp3radio://www.wdr.de/wdrlive/media/einslive.m3u" ),
            Array( ('name') => "1LIVE DIGGI", 
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s45087q.png",
                   ('url')  => "x-rincon-mp3radio://www.wdr.de/wdrlive/media/mp3/1live-diggi.m3u" ),
            Array( ('name') => "917xfm",   
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s85104q.png",
                   ('url')  => "x-rincon-mp3radio://live96.917xfm.de" ),
            Array( ('name') => "Antenne 1",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s25770q.png",
                   ('url')  => "x-rincon-mp3radio://stream.antenne1.de/stream1/livestream.mp3" ),
		    Array( ('name') => "AC/DC Collection",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s256712.png",
                   ('url')  => "x-rincon-mp3radio://streams.radiobob.de/bob-acdc/mp3-192/mediaplayer" ),
            Array( ('name') => "Antenne Bayern",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s42824q.png",
                   ('url')  => "x-rincon-mp3radio://mp3channels.webradio.antenne.de/antenne" ),
            Array( ('name') => "Antenne MV",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s16539q.png",
                   ('url')  => "x-rincon-mp3radio://streams.antennemv.de/antennemv-live/mp3-192/amv" ),
            Array( ('name') => "Antenne Thueringen",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s25774q.png",
                   ('url')  => "x-rincon-mp3radio://stream.antennethueringen.de/live/mp3-192"), 
            Array( ('name') => "Bayern 3",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s14991q.png",
                   ('url')  => "x-rincon-mp3radio://streams.br.de/bayern3_2.m3u" ),
            Array( ('name') => "bigFM",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s84203q.png",
                   ('url')  => "x-rincon-mp3radio://srv05.bigstreams.de/bigfm-mp3-96.m3u" ),
            Array( ('name') => "Bremen Vier",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s25565q.png",
                   ('url')  => "x-rincon-mp3radio://httpmedia.radiobremen.de/bremenvier.m3u" ),
            Array( ('name') => "Energy",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s17697q.png",
                   ('url')  => "x-rincon-mp3radio://energyradio.de/nuernberg" ),
            Array( ('name') => "FFH",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s17490q.png",
                   ('url')  => "x-rincon-mp3radio://streams.ffh.de/radioffh/mp3/hqlivestream.m3u" ),
            Array( ('name') => "FFN",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s8954q.png",
                   ('url')  => "x-rincon-mp3radio://player.ffn.de/ffn.mp3" ),
            Array( ('name') => "Hitradio N1",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s25946q.png",
                   ('url')  => "x-rincon-mp3radio://webstream.hitradion1.de/hitradion1" ),
            Array( ('name') => "HR3",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s57109q.png",
                   ('url')  => "x-rincon-mp3radio://metafiles.gl-systemhaus.de/hr/hr3_2.m3u" ),
            Array( ('name') => "HR-Info",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s17489q.png",
                   ('url')  => "x-rincon-mp3radio://www.metafilegenerator.de/HR/hrinfo/mp3/webm.m3u" ),
            Array( ('name') => "KiRaKa",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s55365q.png",
                   ('url')  => "x-rincon-mp3radio://www.wdr.de/wdrlive/media/kiraka.m3u" ),
            Array( ('name') => "MDR1",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s1346q.png",
                   ('url')  => "x-rincon-mp3radio://avw.mdr.de/livestreams/mdr1_radio_sachsen_live_128.m3u" ),
            Array( ('name') => "MDR Jump",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s6634q.png",
                   ('url')  => "x-rincon-mp3radio://www.jumpradio.de/static/webchannel/jump_live_channel_high.m3u"),
            Array( ('name') => "NDR2",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s17492q.png",
                   ('url')  => "x-rincon-mp3radio://www.ndr.de/resources/metadaten/audio/m3u/ndr2.m3u" ),
            Array( ('name') => "N-JOY",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s25531q.png",
                   ('url')  => "x-rincon-mp3radio://www.ndr.de/resources/metadaten/audio/m3u/n-joy.m3u" ),
            Array( ('name') => "planet radio",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s2726q.png",
                   ('url')  => "x-rincon-mp3radio://streams.planetradio.de/planetradio/mp3/hqlivestream.m3u" ),
            Array( ('name') => "Radio 91.2",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s8923q.png",
                   ('url')  => "x-rincon-mp3radio://lokalradiostream.de:8004" ),
            Array( ('name') => "Radio BOB!",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s96189q.png",
                   ('url')  => "x-rincon-mp3radio://streams.radiobob.de/bob-live/mp3-192/mediaplayer" ),
            Array( ('name') => "Radio Duisburg",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s78341q.png",
                   ('url')  => "x-rincon-mp3radio://edge.live.mp3.mdn.newmedia.nacamar.net/ps-radioduisburg/livestream.mp3.m3u" ),
            Array( ('name') => "Radio Essen",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s47789q.png",
                   ('url')  => "x-rincon-mp3radio://edge.live.mp3.mdn.newmedia.nacamar.net/ps-radioessen/livestream.mp3.m3u" ),
            Array( ('name') => "Radio Hochstift",
                   ('logo') => "https://cdn-radiotime-logos.tunein.com/s84595q.png",
                   ('url')  => "x-rincon-mp3radio://www.radiohochstift.de/worx/mobile/stream.m3u" ),
            Array( ('name') => "Radio Lippe",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s96523q.png",
                   ('url')  => "x-rincon-mp3radio://edge.live.mp3.mdn.newmedia.nacamar.net/ps-radiolippe/livestream.mp3" ),
            Array( ('name') => "Radio Top40",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s18355q.png",
                   ('url')  => "x-rincon-mp3radio://stream.radiotop40.de/live/mp3-192"),
            Array( ('name') => "RPR1",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s9014q.png",
                   ('url')  => "x-rincon-mp3radio://rpr1.fmstreams.de/stream1.m3u" ),
            Array( ('name') => "SWR1 BW",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s20291q.png",
                   ('url')  => "x-rincon-mp3radio://mp3-live.swr.de/swr1bw_m.m3u" ),
            Array( ('name') => "SWR1 RP",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s1561q.png",
                   ('url')  => "x-rincon-mp3radio://mp3-live.swr.de/swr1rp_m.m3u" ),
            Array( ('name') => "SWR3",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s24896q.png",
                   ('url')  => "x-rincon-mp3radio://mp3-live.swr3.de/swr3_m.m3u" ),
            Array( ('name') => "WDR2",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s2680q.png",
                   ('url')  => "x-rincon-mp3radio://www.wdr.de/wdrlive/media/wdr2.m3u" ),
            Array( ('name') => "WDR2 BI",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s2680q.png",
                   ('url')  => "x-rincon-mp3radio://www.wdr.de/wdrlive/media/wdr2_bielefeld.m3u" ),
            Array( ('name') => "YouFM",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s24878q.png",
                   ('url')  => "x-rincon-mp3radio://metafiles.gl-systemhaus.de/hr/youfm_2.m3u" ),
            Array( ('name') => "Deutschlandfunk",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s42828q.png",
                   ('url')  => "x-rincon-mp3radio://www.dradio.de/streaming/dlf.m3u " ),
            Array( ('name') => "OE3",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s8007q.png",
                   ('url')  => "x-rincon-mp3radio://mp3stream7.apasf.apa.at:8000" ),
            Array( ('name') => "Sunshine Live",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s10637q.png",
                   ('url')  => "x-rincon-mp3radio://stream.hoerradar.de/sunshinelive-mp3-128" ),
            Array( ('name') => "Sunshine Live - classics",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s237965q.png",
                   ('url')  => "x-rincon-mp3radio://stream.hoerradar.de/sunshine-classics-mp3-128" ),
            Array( ('name') => "Sunshine Live - trance",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s237967q.png",
                   ('url')  => "x-rincon-mp3radio://stream.hoerradar.de/sunshine-trance-mp3-128" ),
            Array( ('name') => "A State Of Trance",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s252026q.png",
                   ('url')  => "x-sonosapi-stream:s142421?sid=254" ),
            Array( ('name') => "RevivalKult",
                   ('logo') => "http://cdn-radiotime-logos.tunein.com/s186710q.png",
                   ('url')  => "x-sonosapi-stream:s186710?sid=254" )
                         );

  return  $RadioStations ;
}

function get_station_url($name, $RadioStations = null){

  if ( $RadioStations === null ){ $RadioStations = get_available_stations(); };

  foreach ( $RadioStations as $key => $val ) {
      if ($val['name'] === $name) {
          return $RadioStations[$key]['url'];
      }
  }
}

?>
